
services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    hostname: minio
    restart: ${RESTART_POLICY:-always}
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5    
    volumes:
      - minio_data_storage:/data
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      # - MINIO_BROWSER_REDIRECT_URL=https://object-panel.docker.localhost
      # - MINIO_SERVER_URL=https://object.docker.localhost
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.myminio.entrypoints=websecure
      - traefik.http.routers.myminio.rule=Host(`object.docker.localhost`)
      - traefik.http.routers.myminio.service=myminio
      - traefik.http.services.myminio.loadbalancer.server.port=9000

      - traefik.http.routers.myminioadmin.entrypoints=websecure
      - traefik.http.routers.myminioadmin.rule=Host(`object-panel.docker.localhost`)
      - traefik.http.routers.myminioadmin.service=myminioadmin
      - traefik.http.services.myminioadmin.loadbalancer.server.port=9001


networks:
  proxy:
    name: proxy
    external: true

volumes:
  minio_data_storage:
    name: minio_data_storage